FROM ubuntu:14.04

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN sudo apt-get update && sudo apt-get install -y git build-essential libboost-all-dev libssl-dev

RUN mkdir /git && cd /git && sudo git clone https://github.com/reddink/reddcoin-seeder.git && sudo chmod 777 * -R

USER root

RUN echo "cd /git/reddcoin-seeder" > /git/reddcoin-seeder/make.sh && echo "sudo make" >> /git/reddcoin-seeder/make.sh && sudo chmod 777 /git/reddcoin-seeder/make.sh

RUN /git/reddcoin-seeder/make.sh

EXPOSE 53/udp

#test
#ENTRYPOINT /git/reddcoin-seeder/dnsseed -h seeder.redd.ink -n 54.152.97.192 -p 53
